my_string = input('Введите строку: ')
print('Длина вашей строки ' + str(len(my_string)))
print('Ваша строка в верхнем регистре:', my_string.upper())
print('Ваша строка в нижнем регистре:', my_string.lower())
print('Первый символ вашей строки:', my_string[0])
print('Последний символ вашей строки:', my_string[-1] )